---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TERRAFORM_DIR: "./terraform"
  ANSIBLE_DIR: './ansible'

includes:
  terraform:
    taskfile: ./.taskfiles/terraform/taskfile.yaml
    dir: "{{.TERRAFORM_DIR}}"
    aliases: [tf]
  ansible:
    taskfile: ./.taskfiles/ansible/taskfile.yaml
    dir: "{{.ANSIBLE_DIR}}"
    aliases: [ans]

tasks:
  lint:
    desc: Performs lint testing on the YAML files in the repository using the yamllint tool to ensure proper formatting and syntax.
    preconditions:
      - sh: "which yamllint"
        msg: "yamllint {{.PATH_ERROR}}"
    cmds:
      - yamllint -c ./.yamllint .

  default:
    silent: true
    cmd: task -l
