---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TERRAFORM_DIR: "./terraform"
  ANSIBLE_DIR: './ansible'

includes:
  terraform:
    taskfile: ./.taskfiles/terraform/taskfile.yaml
    dir: "{{.TERRAFORM_DIR}}"
    aliases: [tf]
  ansible:
    taskfile: ./.taskfiles/ansible/taskfile.yaml
    dir: "{{.ANSIBLE_DIR}}"
    aliases: [ans]

tasks:
  default:
    silent: true
    cmd: task -l