---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TERRAFORM_DIR: "./terraform"

includes:
  terraform:
    taskfile: ./.taskfiles/terraform/taskfile.yaml
    dir: "{{.TERRAFORM_DIR}}"
    aliases: [tf]

tasks:
  default:
    silent: true
    cmd: task -l