---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  bootstrap-data-disk:
    desc: "Setup data disk"
    cmds:
      - ansible-playbook -i {{.INVENTORY}} bootstrap-data-disk.yaml
    requires:
      vars: [INVENTORY]

  install-k3s-agents:
    desc: "Setup K3S agents"
    cmds:
      - ansible-playbook k3s.orchestration.site -D -i k3s_inventory.yaml -l agent {{.CLI_ARGS}}
    prompt: "Are you sure? - Run with -C first"
