---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.1/charts/other/app-template/values.schema.json
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
  ingress:
    main:
      enabled: true    
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: &host homepage.k8s.home.lauer.dk
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Development:
            - ArgoCD:
                href: https://argocd.k8s.home.lauer.dk
                description: Continuous deployment
                icon: argocd.svg
        bookmarks.yaml: |
          - Homelab:
            - Public homelab repository:
              - href: https://github.com/lauer/homelab
                icon: github.svg