apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/lauer/homelab
        revision: testing-apps
        directories:
          - path: k8s/services/observability/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        homeops.services.component: observability
    spec:
      project: default
      source:
        repoURL: https://github.com/lauer/homelab
        targetRevision: testing-apps
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true