apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/appset-database.yaml
  - network/appset-network.yaml
  - observability/appset-observability.yaml
  - security/appset-security.yaml
  - tools/appset-tools.yaml