### ArgoCD Taskfile
---
version: '3'

silent: true

tasks:
  login:
    preconditions:
    - sh: 'which argocd'
      msg: 'argocd {{.PATH_ERROR}}'    
    cmds:
    - argocd login argocd.k8s.home.lauer.dk --username {{.ARGOCD_USERNAME}} --password {{.ARGOCD_PASSWORD}}
    vars:
      ARGOCD_USERNAME: admin
      ARGOCD_PASSWORD: 
        sh: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
  
  password:
    cmds:
    - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
    ignore_error: true

  apps: 
    desc: Show ArgoCD apps
    cmd: "kubectl -n argocd get apps"

  create-namespace:
    desc: Create namespace which can be controlled by ArgoCD - APP_NAMESPACE=namespace
    cmd: kubectl create namespace {{.APP_NAMESPACE}} --dry-run=client -o json|jq '.metadata += {"labels":{"argocd.argoproj.io/managed-by":"argocd"}}' | kubectl apply -f -
    requires:
      vars: [APP_NAMESPACE]
