apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts/
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |
        image:
          repository: traefik/whoami
          tag: latest

        service:
          main:
            enabled: true
            ports:
              http:
                port: 80

        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - host: whoami.k8s.home.lauer.dk
                paths:
                  - path: /
                    pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true