app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: traefik/whoami
            tag: latest

  service:
    main:
      controller: main
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: whoami.k8s.home.lauer.dk
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http