apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/lauer/homelab
        revision: play
        directories:
          - path: k8s/services/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        homeops.services.component: apps
    spec:
      project: default
      source:
        repoURL: https://github.com/lauer/homelab
        targetRevision: play
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: 'app-{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true