apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/projects

  - base/argo-cd-ui-ingress.yaml
  - base/ssl-certificate.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.10/manifests/install.yaml

namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.14.10
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value: "--insecure"
  target:
    kind: Deployment
    name: argocd-server

## Initial admin password:
# kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath={.data.password} | base64 -d

## Simple start guide
# https://medium.com/@muppedaanvesh/a-hands-on-guide-to-argocd-on-kubernetes-part-1-%EF%B8%8F-7a80c1b0ac98
